### ISSUE TITLE
[UnionGenerators] [Bug] Can't create instance of nullable type

### ISSUE THREAD

**Issue by pedro-de-rycker-sncf** [PaulBraetz/RhoMicro.CodeAnalysis#23]
When I had this attribute to my union :
[UnionType<long>(Alias = "Long", Options = UnionTypeOptions.Nullable)]

I don't get any build errors but at runtime on using a long? I get this error :
System.InvalidOperationException: Unable to create an instance of ReportPortal.WebApi.Services.Interfaces.Unions.RowValue from an instance of System.Nullable`1[System.Int64].

I think the problem comes that Create(long? value) doesn't exist so it falls back on Create<TValue>(TValue value)

**Comment by SleepWellPupper** [comment]
Can you please provide an MVE of your union type as well as how you are instantiating your union type?

`[UnionType(Alias = "Long", Options = UnionTypeOptions.Nullable)]` is not a valid union type annotation.

Also, assuming you are actually using `[UnionType<long?>(Alias = "Long", Options = UnionTypeOptions.Nullable)]`, using `UnionTypeOptions.Nullable` on value types is not required, as per the documentation (only needed for nullable reference types).

Also, `[UnionType<long?>]` should generate a factory `Create(long? value)`. This means that when using factory methods with `long` values, overload resolution will prioritize the generic `Create<T>(T value)` method. Since you provided an error referencing a `long?` argument however, I am confused as to how overload resolution would select `Create<T>(T)` over `Create(long?)`.

I need a little more detail to reproduce the issue, write a regression test for it and fix it.

**Comment by SleepWellPupper** [comment]
You were using `[UnionType<long>(Alias = "Long", Options = UnionTypeOptions.Nullable)]`. I have added a diagnostic and additional comments on the options that warns about this erroneous use of the option.

Fixed : https://github.com/PaulBraetz/RhoMicro.CodeAnalysis/releases/tag/15.0.1
